repos:
  - url: 'git@github.com:missedone/multi-git-sync-test.git'
    branch: main
    auth:
      user: git
      privateKeyFile: ~/.ssh/id_rsa
    destDir: ./out/sshclone/multi-git-sync-test
    schedule: '*/1 * * * *'
