version: "2"
run:
  modules-download-mode: mod
linters:
  enable:
    - dupl
    - goconst
    - gocyclo
    - gosec
    - lll
    - misspell
    - nakedret
    - prealloc
    - unconvert
    - unparam
  settings:
    gosec:
      excludes:
        - G402
    lll:
      line-length: 120
      tab-width: 1
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - .*_test\.go$
      - build
      - docs
      - logging/tint
      - oidc
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - .*_test\.go$
      - build
      - docs
      - logging/tint
      - oidc
      - third_party$
      - builtin$
      - examples$
