repos:
  - url: 'https://github.com/missedone/multi-git-sync-test.git'
    branch: main
    subPath: foo
    depth: 1
    auth:
      user: private
      accessToken: {{ getEnv "PAT" }}
    destDir: ./out/sparse-checkout/multi-git-sync-test
    schedule: '*/1 * * * *'
